//! NQueens via boolean GCFLOBDDs, ported from the main engine's `n_queens`
//! example to the compile-time-grammar crate.
//!
//! The grammars (`Q{n}Row`, `Q{n}Board` for n = 8..=14) are generated by
//! `build.rs` into `$OUT_DIR/queens_grammars.rs` and `include!`d below — the
//! compile-time analogue of the main engine's runtime `S2 -> S1 (×n); S1 -> a
//! (×n)` "default" grammar.

use gcflobdd::gcflobdd::Gcflobdd;
use gcflobdd::grammar::{GhddGrammar, Unit};

include!(concat!(env!("OUT_DIR"), "/queens_grammars.rs"));

/// Build the NQueens constraint diagram over the `n × n` board (variable
/// `i * n + j` = "a queen sits on row `i`, column `j`") and return one satisfying
/// placement. `Root` is the board grammar, whose `NUM_VARS` must be `n * n`.
fn solve<Root: GhddGrammar>(n: usize) -> Vec<Option<bool>> {
    assert_eq!(Root::NUM_VARS, n * n, "grammar must have n*n variables");

    let vars: Vec<Vec<Gcflobdd<Root>>> = (0..n)
        .map(|i| (0..n).map(|j| Gcflobdd::<Root>::mk_projection(i * n + j)).collect())
        .collect();

    // each row holds at least one queen
    let or_batch: Vec<Gcflobdd<Root>> = (0..n)
        .map(|i| {
            (0..n).fold(Gcflobdd::<Root>::mk_false(), |acc, j| acc.mk_or(&vars[i][j]))
        })
        .collect();

    // for each cell, "queen here ⇒ no queen attacks it" along row, column, and
    // both diagonals
    let mut imp_batch: Vec<Vec<Gcflobdd<Root>>> = Vec::with_capacity(n);
    for i in 0..n {
        let mut row = Vec::with_capacity(n);
        for j in 0..n {
            let mut cell = Gcflobdd::<Root>::mk_true();

            // same column
            for l in 0..n {
                if l != j {
                    cell = cell.mk_and(&vars[i][j].mk_implies(&vars[i][l].mk_not()));
                }
            }
            // same row
            for k in 0..n {
                if k != i {
                    cell = cell.mk_and(&vars[i][j].mk_implies(&vars[k][j].mk_not()));
                }
            }
            // up-right diagonal
            for k in 0..n {
                let ll = k as i32 - i as i32 + j as i32;
                if (0..n as i32).contains(&ll) && k != i {
                    cell = cell.mk_and(&vars[i][j].mk_implies(&vars[k][ll as usize].mk_not()));
                }
            }
            // down-right diagonal
            for k in 0..n {
                let ll = i as i32 + j as i32 - k as i32;
                if (0..n as i32).contains(&ll) && k != i {
                    cell = cell.mk_and(&vars[i][j].mk_implies(&vars[k][ll as usize].mk_not()));
                }
            }
            row.push(cell);
        }
        imp_batch.push(row);
    }

    let mut queen = Gcflobdd::<Root>::mk_true();
    for cond in &or_batch {
        queen = queen.mk_and(cond);
    }
    for row in &imp_batch {
        for cell in row {
            queen = queen.mk_and(cell);
        }
    }

    queen
        .find_one_satisfiable_assignment()
        .expect("NQueens is satisfiable for n >= 4")
}

/// Assert `path` (a `Some(true)` per queen) is a legal `n`-queens placement.
fn assert_valid(path: &[Option<bool>], n: usize) {
    let queens: Vec<(usize, usize)> = (0..n)
        .flat_map(|i| (0..n).map(move |j| (i, j)))
        .filter(|&(i, j)| path[i * n + j] == Some(true))
        .collect();

    assert_eq!(queens.len(), n, "exactly n queens, got {:?}", queens);

    for a in 0..queens.len() {
        for b in (a + 1)..queens.len() {
            let (r1, c1) = queens[a];
            let (r2, c2) = queens[b];
            assert_ne!(r1, r2, "two queens share a row");
            assert_ne!(c1, c2, "two queens share a column");
            assert_ne!(
                r1 as i32 - c1 as i32,
                r2 as i32 - c2 as i32,
                "two queens share a ↘ diagonal"
            );
            assert_ne!(
                r1 + c1,
                r2 + c2,
                "two queens share a ↗ diagonal"
            );
        }
    }
}

#[test]
fn n_queens_8() {
    assert_valid(&solve::<Q8Board>(8), 8);
}

#[test]
fn n_queens_9() {
    assert_valid(&solve::<Q9Board>(9), 9);
}

#[test]
fn n_queens_10() {
    assert_valid(&solve::<Q10Board>(10), 10);
}

// Larger boards build the same way but take longer; run them explicitly with
// `cargo test --release -- --ignored`.
#[test]
#[ignore = "slow; exercises the larger generated grammars"]
fn n_queens_11() {
    assert_valid(&solve::<Q11Board>(11), 11);
}

#[test]
#[ignore = "slow; exercises the larger generated grammars"]
fn n_queens_12() {
    assert_valid(&solve::<Q12Board>(12), 12);
}

#[test]
#[ignore = "slow; exercises the larger generated grammars"]
fn n_queens_13() {
    assert_valid(&solve::<Q13Board>(13), 13);
}

#[test]
#[ignore = "slow; exercises the larger generated grammars"]
fn n_queens_14() {
    assert_valid(&solve::<Q14Board>(14), 14);
}
