#ifndef GCFLOBDD_H
#define GCFLOBDD_H

#pragma once

/* Auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>
#include <stdint.h>

typedef struct gcfl_bool_t gcfl_bool_t;

typedef struct gcfl_session_t gcfl_session_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

struct gcfl_session_t *gcfl_session_new_bdd(uintptr_t num_vars);

/**
 * Create a session from an array of NUL-terminated production-rule strings.
 * Returns NULL on parse failure or if any rule pointer is NULL.
 */
struct gcfl_session_t *gcfl_session_new_from_rules(const char *const *rules, uintptr_t n_rules);

void gcfl_session_free(struct gcfl_session_t *session);

void gcfl_session_gc(struct gcfl_session_t *session);

uintptr_t gcfl_session_node_count(const struct gcfl_session_t *session);

struct gcfl_bool_t *gcfl_bool_mk_true(struct gcfl_session_t *session);

struct gcfl_bool_t *gcfl_bool_mk_false(struct gcfl_session_t *session);

struct gcfl_bool_t *gcfl_bool_mk_projection(struct gcfl_session_t *session, uintptr_t var_index);

struct gcfl_bool_t *gcfl_bool_clone(const struct gcfl_bool_t *bdd);

void gcfl_bool_free(struct gcfl_bool_t *bdd);

bool gcfl_bool_eq(const struct gcfl_bool_t *a, const struct gcfl_bool_t *b);

struct gcfl_bool_t *gcfl_bool_not(const struct gcfl_bool_t *bdd);

struct gcfl_bool_t *gcfl_bool_and(struct gcfl_session_t *session,
                                  const struct gcfl_bool_t *lhs,
                                  const struct gcfl_bool_t *rhs);

struct gcfl_bool_t *gcfl_bool_or(struct gcfl_session_t *session,
                                 const struct gcfl_bool_t *lhs,
                                 const struct gcfl_bool_t *rhs);

struct gcfl_bool_t *gcfl_bool_xor(struct gcfl_session_t *session,
                                  const struct gcfl_bool_t *lhs,
                                  const struct gcfl_bool_t *rhs);

struct gcfl_bool_t *gcfl_bool_nand(struct gcfl_session_t *session,
                                   const struct gcfl_bool_t *lhs,
                                   const struct gcfl_bool_t *rhs);

struct gcfl_bool_t *gcfl_bool_nor(struct gcfl_session_t *session,
                                  const struct gcfl_bool_t *lhs,
                                  const struct gcfl_bool_t *rhs);

struct gcfl_bool_t *gcfl_bool_xnor(struct gcfl_session_t *session,
                                   const struct gcfl_bool_t *lhs,
                                   const struct gcfl_bool_t *rhs);

struct gcfl_bool_t *gcfl_bool_implies(struct gcfl_session_t *session,
                                      const struct gcfl_bool_t *lhs,
                                      const struct gcfl_bool_t *rhs);

/**
 * Find a satisfying assignment.
 *
 * On success writes the number of variables to `*out_len` and returns a
 * heap-allocated array of length `*out_len` where each byte is:
 *   - `0` = must be false
 *   - `1` = must be true
 *   - `-1` (as int8) = don't care
 * The caller must release the array with `gcfl_assignment_free`.
 * On failure (unsatisfiable) returns NULL and writes 0 to `*out_len`.
 */
int8_t *gcfl_bool_find_sat(const struct gcfl_bool_t *bdd, uintptr_t *out_len);

void gcfl_assignment_free(int8_t *ptr, uintptr_t len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* GCFLOBDD_H */
